name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: bills
      DB_USER: root
      DB_PASSWORD: root

    steps:
        if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      - name: Update and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server mysql-client -y

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD

      - name: Execute SQL script
        run: |
          sudo mysql -u$DB_USER -p$DB_PASSWORD $DB_DATABASE < ./test.sql

      - name: Verify table creation
        run: |
          TABLE_COUNT=$(sudo mysql -u$DB_USER -p$DB_PASSWORD --execute="USE $DB_DATABASE; SHOW TABLES;" | grep -c -e 'categories' -e 'customer')
          if [ "$TABLE_COUNT" -ne 2 ]; then
            echo "Error: Tables were not created successfully!"
            exit 1
          else
            echo "Tables created successfully."
          fi

      - name: Verify data insertion into the customer table
        run: |
          CUSTOMER_COUNT=$(sudo mysql -u$DB_USER -p$DB_PASSWORD --execute="USE $DB_DATABASE; SELECT COUNT(*) FROM customer;" | tail -n 1)
          if [ "$CUSTOMER_COUNT" -lt 4 ]; then
            echo "Error: Data insertion into the customer table failed!"